using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace excuseMaker
{
    internal class placeToStoreSentences
    {
        public static string[] firstSentence =
        {
            "I’m so sorry, I was halfway out the door when",
            "You won’t believe the sequence of events, but",
            "I’m running a bit behind because",
            "Please forgive my tardiness, I got caught up when",
            "My morning took a sharp turn for the weird because",
            "I would have been here ten minutes early, but",
            "I’m currently dealing with a minor crisis because",
            "My departure was delayed indefinitely because",
            "I’m stepping in just now because",
            "I’ve had a bit of a logistical nightmare because",
            "Fate conspired against my punctuality today because",
            "I was just about to start the car when",
            "Things went slightly off the rails this morning because",
            "I’m fashionably (and accidentally) late because",
            "I’m lagging behind schedule today because",
            "My alarm clock and I had a disagreement because",
            "I had to make an emergency U-turn because",
            "I’m currently moving at a snail’s pace because",
            "My routine was completely disrupted because",
            "I’m arriving in installments because",
            "I lost all track of time because",
            "I was ready to go, but then",
            "The universe decided I needed a challenge because",
            "My commute became an odyssey because",
            "I’m just pulling up now because",
            "I had a small mechanical failure because",
            "Everything was going fine until",
            "I’m at the mercy of the elements because",
            "I had a momentary lapse in navigation because",
            "My exit strategy failed because",
            "I’m trailing behind because",
            "I had to pause my entire life because",
            "I’m late, and I have a very specific reason:",
            "My morning was perfectly scheduled until",
            "I was sidelined by a strange occurrence because",
            "I’m making a grand entrance late because",
            "My internal clock was reset because",
            "I’m playing catch-up today because",
            "My front door became an obstacle because",
            "I was literally on my way when",
            "I’ve had a series of unfortunate events because",
            "I am deeply embarrassed to say that",
            "My travel plans were thwarted because",
            "I’m arriving late with a heavy heart because",
            "I’m just reaching the destination because",
            "My timing was sabotaged because",
            "I had to stop everything because",
            "I’m lagging by about twenty minutes because",
            "I was derailed by a minor miracle because",
            "My transit was interrupted because",
            "I found myself in a bizarre predicament because",
            "I’m operating on a delay because",
            "My preparations were interrupted because",
            "I had to double-back home because",
            "I’m running on a different timezone because",
            "I was waylaid by a sudden realization that",
            "My momentum was halted because",
            "I’m a victim of circumstance because",
            "I’m scrambling to get there because",
            "I was briefly incapacitated by the fact that",
            "I’m struggling with my schedule because",
            "I had a brief encounter with chaos because",
            "My start was delayed because",
            "I was caught in a loop because",
            "I’m running behind for the first time because",
            "I’m moving as fast as I can since",
            "My morning was going too smoothly until",
            "I had a very strange realization because",
            "I’m just now escaping the house because",
            "I’m a little behind the curve because",
            "I was just tying my shoes when",
            "I had a complete equipment failure because",
            "I’m late but I have a great story about how",
            "I’m showing up now because",
            "My path was blocked because",
            "I’m currently navigating a detour because",
            "I was almost there, but",
            "I’m arriving later than intended because",
            "I had to wait for a professional because",
            "My morning became a puzzle because",
            "I’m behind schedule due to the fact that",
            "I was fully prepared, but then",
            "I’m just getting through the door because",
            "I had to deal with a domestic issue because",
            "I’m moving slow today because",
            "I had a sudden change in plans because",
            "I’m feeling the pressure because",
            "I was about to leave when I noticed",
            "My transit took longer than expected because",
            "I’m arriving under duress because"
        };

        public static string[] secondSentence =
        {
            "my cat decided to fall asleep on my car keys ",
            "the neighbor’s sprinkler system went rogue ",
            "I accidentally put my shoes on the wrong feet ",
            "there was a localized parade of ducks in the road ",
            "my GPS insisted that I drive through a fountain ",
            "I forgot how to tie a necktie for ten minutes ",
            "a very persistent squirrel wouldn't let me leave ",
            "I spent too long trying to find a matching sock ",
            "my coffee cup developed a mind of its own ",
            "the elevator stopped to have a 'moment of reflection '",
            "I got into a debate with a smart-home device ",
            "a flock of pigeons refused to move from my driveway ",
            "I had to save a ladybug from a precarious situation ",
            "my shoelaces tied themselves into a Gordian knot ",
            "I forgot where I parked my own feet ",
            "the fog was so thick I thought I was in a movie ",
            "my toaster staged a protest and burned everything ",
            "I couldn't remember if I’d actually brushed my teeth ",
            "the local traffic light was stuck on red for an eternity ",
            "I had to help an elderly neighbor with their Wi-Fi ",
            "my dog staged a sit-in in front of the door ",
            "I realized I was wearing my shirt inside out ",
            "a mystery box arrived and I had to see what was inside ",
            "I was distracted by a particularly beautiful sunrise ",
            "my car door was temporarily frozen shut ",
            "I took a wrong turn and ended up in another county ",
            "the zipper on my bag decided to quit its job ",
            "I had to clean up a sudden flour explosion in the kitchen ",
            "my phone decided to update its entire existence ",
            "I was searching for a pen that was behind my ear ",
            "the wind was blowing exactly in the wrong direction ",
            "I had to wait for my favorite song to finish ",
            "my belt loop got caught on the door handle ",
            "I was mesmerized by a spider spinning a web ",
            "there was an unexpected road closure for a marathon ",
            "my glasses went missing while I was wearing them ",
            "I accidentally brewed a pot of decaf and had to restart ",
            "a neighbor’s cat was judging me from the fence ",
            "I had to double-check that the stove was off five times ",
            "the stairs felt significantly longer than usual ",
            "I got stuck watching a tutorial on how to boil water ",
            "my umbrella turned inside out in a gentle breeze ",
            "I found a very old photo and got sentimental ",
            "the trash bag broke at the worst possible moment ",
            "I was trying to remember the name of a famous actor ",
            "a bird was tapping on my window for attention ",
            "my reflection in the mirror was too distracting ",
            "I had to reorganize my spice rack alphabetically ",
            "my shoelaces snapped right as I was pulling them ",
            "I couldn't find my wallet, which was in my hand ",
            "the automatic garage door was feeling temperamental ",
            "I had to escort a stray turtle across the street ",
            "my morning smoothie ended up on the ceiling ",
            "I forgot how to operate the door lock for a second ",
            "the radio played three of my favorite songs in a row ",
            "I was convinced it was Saturday for a solid hour ",
            "my laptop wouldn't stop making a chirping sound ",
            "I had to help a delivery driver find a ghost address ",
            "my plant looked a little thirsty and I got carried away ",
            "I was trying to solve a crossword puzzle in my head ",
            "a low-flying cloud made visibility very difficult ",
            "my iron wouldn't heat up, then it heated up too much ",
            "I had to wait for the floor to dry after a spill ",
            "I got into a staring contest with a very bold rabbit ",
            "my favorite mug was in the back of the dishwasher ",
            "I had to find a specific pair of lucky earrings ",
            "the driveway was blocked by a mountain of leaves ",
            "I was distracted by a very intense documentary ",
            "my watch stopped and I lost track of reality ",
            "I had to change because I spilled water on myself ",
            "the local bakery smelled too good to pass by ",
            "I was checking the tire pressure for way too long ",
            "the hallway smelled like cinnamon and I got confused ",
            "I was trying to find the end of the masking tape ",
            "a sudden gust of wind blew my hat into a tree ",
            "I had to rescue a moth from a lamp ",
            "the ink in my pen ran out mid-sentence ",
            "I was waiting for my hair to agree with my hat ",
            "a very large leaf fell on my windshield ",
            "I was practicing my 'surprised' face in the mirror ",
            "the mail carrier had some very interesting stories ",
            "I had to re-tie my scarf several times ",
            "my keys were hiding in the refrigerator ",
            "I was over-analyzing a dream I had about cheese ",
            "the sidewalk was being cleaned by a very slow robot ",
            "I had to find a charger for my electric toothbrush ",
            "a butterfly led me in the wrong direction ",
            "I was trying to remember why I walked into the room ",
            "my phone case was on upside down ",
            "I simply forgot that time exists as a concept "
        };

    }
}
